### ISSUE TITLE
Possible Improvements

### ISSUE THREAD

**Issue by muadpn** [muadpn/minar-cruise#61]
## Home Page
1. chore: Change Hero Video as client suggest.
2. fix: Remove quick navigation menu.
3. feat: Implement new Home Page Design.
4. feat: Whats app Chat Button

## Navigation's
1. fix: Fix Navigation Links [facilities, About, Contact]
2. fix: Footer Navigation links [News And Blogs, Facilities, About Us].

## Package Page.
1. feat: add in Package Image Data Carousal.
2. chore: Image Responsiveness.
3. chore:  Maintain or add More contents in Package Data (seeding)
4. chore: Terms and condition styles to be list inside.
5. fix: Remove Review Score Component.

## Package / Package Card.
1. feat: Add accept consent's for Monsoon Restrictions.
2. feat: Add Accept Privacy policy.
3. feat: Add Blocked Schedule to be Disabled.
4. feat: Add Adult / Count pricing above Inputs.
5. feat: Add Auto calculation for expected total.

**Comment by neilnicky** [comment]
I can fix the Navigation's, both the footer and above ones.

**Comment by muadpn** [comment]
Please feel free to take up any of the following Issues that you can work on @amjuz

**Comment by amjuz** [comment]
I have already completed some of the issues that are posted, and two of them are still remaining.
I am attaching the details below and will be working on the issues that are yet to be completed 

**Package / Package Card.**

> Completed:-

- feat: Add accept consent's for Monsoon Restrictions.
- feat: Add Accept Privacy policy.
- feat: Add Auto calculation for expected total.
 

> To be resolved:-

- feat: Add Adult / Count pricing above Inputs.
- feat: Add Blocked Schedule to be Disabled.
